<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to Wishlist_product-one-thumb</name>
   <tag></tag>
   <elementGuidId>b40e3f88-7d14-4fdf-8bd3-70e68a973a8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='noo-site']/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.noo-product-item.one.noo-product-sm-4.not_featured.post-1485.product.type-product.status-publish.has-post-thumbnail.product_cat-t-shirt.product_tag-t-shirt.product_tag-women.has-featured.instock.shipping-taxable.purchasable.product-type-variable > div.noo-product-inner > div.noo-product-thumbnail > div.noo-product-slider.owl-carousel.owl-theme > div.owl-wrapper-outer.autoHeight > div.owl-wrapper > div.owl-item.active > a.hover-device > img.product-one-thumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a87ecaa-b53f-43d2-b5bd-62743bd4e44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>b8b024e2-ff4e-4882-b5d6-5b21b5ec9c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>3cc3df27-9797-4875-847e-62e9844628ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/wp-content/uploads/2019/04/black-lux-graphic-t-shirt-300x300.jpg</value>
      <webElementGuid>c4b92eb0-aea3-4a40-8c7e-50fa528c2530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-one-thumb</value>
      <webElementGuid>14007e6b-d406-4c52-a774-39f50ca35c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>1423ce04-0cee-4878-8d88-f75b5bb7e17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>5a87f1c2-6245-42d2-ac24-f3315be90cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/wp-content/uploads/2019/04/black-lux-graphic-t-shirt-300x300.jpg 300w, https://shop.demoqa.com/wp-content/uploads/2019/04/black-lux-graphic-t-shirt-150x150.jpg 150w, https://shop.demoqa.com/wp-content/uploads/2019/04/black-lux-graphic-t-shirt-650x650.jpg 650w, https://shop.demoqa.com/wp-content/uploads/2019/04/black-lux-graphic-t-shirt-100x100.jpg 100w</value>
      <webElementGuid>ab929775-28d8-4172-9e67-9a6c790e5225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>6b672485-906f-4471-99e1-301953650700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noo-site&quot;)/div[@class=&quot;noo-container-shop noo-shop-wrap&quot;]/div[@class=&quot;noo-row&quot;]/div[@class=&quot;noo-md-12 one&quot;]/div[@class=&quot;products noo-row&quot;]/div[@class=&quot;noo-product-item one noo-product-sm-4 not_featured post-1485 product type-product status-publish has-post-thumbnail product_cat-t-shirt product_tag-t-shirt product_tag-women has-featured  instock shipping-taxable purchasable product-type-variable&quot;]/div[@class=&quot;noo-product-inner&quot;]/div[@class=&quot;noo-product-thumbnail&quot;]/div[@class=&quot;noo-product-slider owl-carousel owl-theme&quot;]/div[@class=&quot;owl-wrapper-outer autoHeight&quot;]/div[@class=&quot;owl-wrapper&quot;]/div[@class=&quot;owl-item active&quot;]/a[@class=&quot;hover-device&quot;]/img[@class=&quot;product-one-thumb&quot;]</value>
      <webElementGuid>a9cbaa67-c567-4211-883f-bd6a133c4fdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noo-site']/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>5ac10e93-4fb9-41d9-8bc0-2f82b746bf46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://shop.demoqa.com/wp-content/uploads/2019/04/black-lux-graphic-t-shirt-300x300.jpg')]</value>
      <webElementGuid>6a357981-66ed-4242-8715-171fdfdfc4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>d7c1f020-ea8b-4afb-b1bf-6c1cd9e8ac40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://shop.demoqa.com/wp-content/uploads/2019/04/black-lux-graphic-t-shirt-300x300.jpg']</value>
      <webElementGuid>65c02317-3fda-40ac-b873-044916190c24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
