<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cart(0)0.00</name>
   <tag></tag>
   <elementGuidId>2f9fc2c5-abce-4659-8345-5f549334562a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-cart']/a/span/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.cart-name-and-total</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78ef93ea-4bff-49b4-8922-7571e3699876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-name-and-total</value>
      <webElementGuid>fb2de0e6-6335-486a-892f-91dcd9ce779e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cart(0)₹0.00</value>
      <webElementGuid>12de525e-3f91-4950-9d2d-058eace1afe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-cart&quot;)/a[@class=&quot;cart-button&quot;]/span[@class=&quot;cart-item&quot;]/span[@class=&quot;cart-name-and-total&quot;]</value>
      <webElementGuid>52560369-fcf8-4953-bce5-e45bcc69b60c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-cart']/a/span/span[2]</value>
      <webElementGuid>3bf2b897-7318-482c-8f2e-06e842e74145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::span[3]</value>
      <webElementGuid>70cabd70-e7dc-444f-aea9-08ba57965071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/following::span[3]</value>
      <webElementGuid>e8cae2da-4edd-4391-a1c5-dcdb1caef0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your shopping bag is empty.'])[1]/preceding::span[3]</value>
      <webElementGuid>79752041-6e59-4c8f-9ac9-3a37b5c5e7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cart(0)']/parent::*</value>
      <webElementGuid>a25459f2-d4c9-4da0-b95d-59ad9b93855f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>b178b433-a6e4-4f1b-8319-d2bd094b7cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cart(0)₹0.00' or . = 'Cart(0)₹0.00')]</value>
      <webElementGuid>2ffc0da2-6723-4641-9ebd-17f695a46763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
